name: Digital Ocan Deployment
on:
  push:
    brances: [master]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      run: |
        echo "Just Hello".
