name: Digital Ocan Deployment
on:
  push:
    brances: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: login
        run: echo "Hello ${{ secrets.HOST }}"
