name: Digital Ocan Deployment
on:
  push:
    brances: [master]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: login
        run: echo "Hello" . ${{ secrets.HOST }}
        uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USER }}
            PORT: ${{ secrets.PORT }}
            password: ${{ secrets.PASSWORD }}
            script: |
                docker -v
